# Generated by Django 5.0.7 on 2024-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublevel_one', models.CharField(max_length=100)),
                ('sublevel_two', models.CharField(max_length=100)),
                ('sublevel_three', models.CharField(max_length=100)),
                ('sublevel_four', models.CharField(max_length=100)),
                ('sublevel_five', models.CharField(max_length=100)),
                ('sublevel_six', models.CharField(max_length=100)),
                ('sublevel_seven', models.CharField(max_length=100)),
                ('sublevel_eight', models.CharField(max_length=100)),
                ('sublevel_nine', models.CharField(max_length=100)),
                ('sublevel_ten', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelsUploadFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='address')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'upload levels',
                'verbose_name_plural': 'upload levels',
                'db_table': 'uploads_levels',
            },
        ),
    ]
