# Generated by Django 5.0.7 on 2024-10-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomicos', '0001_initial'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadagronomicosfilesmodel',
            name='levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.levelsmodel'),
        ),
    ]
