# Generated by Django 5.0.7 on 2024-10-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaliesmodel',
            name='error_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='anomaliesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anomalos'),
        ),
    ]
