# Generated by Django 5.0.7 on 2024-10-12 23:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralSignaturesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('end_date', models.CharField(blank=True, max_length=15, null=True)),
                ('initial_time', models.CharField(blank=True, max_length=15, null=True)),
                ('end_time', models.TimeField()),
                ('initial_temperature', models.FloatField(default=0.0)),
                ('end_temperature', models.FloatField(default=0.0)),
                ('initial_voltage', models.FloatField(default=0.0)),
                ('end_voltage', models.FloatField(default=0.0)),
                ('initial_averages', models.PositiveIntegerField(default=0)),
                ('end_averages', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Spectral Signature Information',
                'verbose_name_plural': 'Spectral Signatures Informations',
                'db_table': 'spectral_signatures_info',
            },
        ),
        migrations.CreateModel(
            name='SpectralSignaturesUploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='spectral_signatures')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Spectral Signature',
                'verbose_name_plural': 'upload files Spectral Signatures',
                'db_table': 'uploads_spectral_signatures',
            },
        ),
        migrations.CreateModel(
            name='SpectralSignaturesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), blank=True, size=None)),
                ('y', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), blank=True, size=None)),
                ('levels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levels.levelsmodel')),
            ],
            options={
                'verbose_name': 'Spectral Signature Data',
                'verbose_name_plural': 'Spectral Signatures Data',
                'db_table': 'spectral_signatures_data',
            },
        ),
    ]
