# Generated by Django 5.0.7 on 2024-10-12 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariablesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=100)),
                ('initial_spectral_range', models.PositiveIntegerField()),
                ('final_spectral_range', models.PositiveIntegerField()),
                ('serie_number', models.CharField(max_length=100)),
                ('bandwidth', models.FloatField(default=0)),
                ('calibration_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.teamsmodels')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.variablesmodels')),
            ],
        ),
    ]
